server {
    listen 80;

    location = / {
        return 301 /delay_and_defeat/;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /delay_and_defeat/index.html;
    }

    error_page 404 /delay_and_defeat/index.html;
}
